# Start with a base image containing Java runtime and Maven
FROM openjdk:17-jdk-slim as build

# Copy the project files into the container
COPY src /laptopshop/spring-mvc/src
COPY pom.xml /laptopshop/spring-mvc

# Set the working directory
WORKDIR /laptopshop/spring-mvc

# Build the application as a WAR file and skip tests
RUN mvn clean package -DskipTests

FROM openjdk:17-slim

# Copy WAR file to the webapps directory in Tomcat
# Ensure that the path to the WAR file matches the actual file name generated by Maven
COPY --from=build /laptopshop/spring-mvc/target/*.war /laptopshop/spring-mvc/app.war

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/laptopshop/spring-mvc/app.war"]