spring.application.name=LaptopShop
#https://spring.io/guides/gs/accessing-data-mysql
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/laptop-database
spring.datasource.username=System.getEnv("DATABASE_USER")
spring.datasource.password=System.getEnv("DATABASE_PASSWORD")
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true
